[project]

name = "chatbot-backend"
revision = "1.0"

[default]

# No provider defined here.
# Will refer to  ~/.config/secretspec/config.toml

[profiles]

[profiles.default]

AI_SECRET = { description = "Shared token between Chatbot Frontend and Backend", required = true }

# Cloudflare
CF_AI_GATEWAY_TOKEN = { description = "Cloudflare Token for access to AI Gateway", required = true }
RAG_SECRET = { description = "Cloudflare Token for access to Vectorize Database", required = true }

# xAI
GROK_TOKEN = { description = "Optional xAI Token for access to grok", required = false }
