[package]

name = "chatbot-utils"
description = "tresr community chatbot shared utilities"
version = "1.0.0"
edition = "2021"
license = "Unlicense"
repository = "https://github.com/tresr-community/chatbot-backend"

[package.metadata.release]

release = false

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]

wasm-opt = true

[lib]

crate-type = ["rlib", "cdylib"]

[dependencies]

worker = "0.6.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.143"

[target.'cfg(target_arch = "wasm32")'.dependencies]

wasm-bindgen = "0.2.100"
