[package]

name = "chatbot-backend"
description = "tresr community chatbot backend"
version = "1.0.0"
edition = "2021"
license = "Unlicense"
repository = "https://github.com/tresr-community/chatbot-backend"

[package.metadata.release]

release = false

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]

wasm-opt = true

[lib]

crate-type = ["cdylib"]

[dependencies]

# Load the shared-libs crate
chatbot-utils = { path = "../../crates/utils" }

# External dependencies
worker = "0.7.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
base64 = "0.22.1"
tokio = { version = "1.49.0", features = ["rt"] }
uuid = { version = "1.21", features = ["v4", "js"] }
nanohtml2text = "0.2"
