---
##################################################
# Name: thumbs.yaml
# Description:
#   A Workflow that posts Thumbs Up/Down comments.
##################################################

name: Thumbs Up/Down

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: read
  checks: read
  deployments: read
  statuses: read

env:
  ORGANISATION: ${{ github.repository_owner }}
  PROJECT: ${{ github.event.repository.name }}

  # Works on pushes or PRs
  BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
  BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}

jobs:
  ##################################################
  # Generate a dynamic Matrix of Cloudflare Workers.
  ##################################################

  matrix:
    name: Worker Matrix

    runs-on: ${{ matrix.os }}

    timeout-minutes: 5
    continue-on-error: false

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
          lfs: false
          persist-credentials: true
          submodules: recursive

      - id: generate_matrix
        name: Generating a matrix of worker names
        run: |
          echo "Generating matrix of worker names..."
          WORKER_NAMES=$(find workers -mindepth 1 -maxdepth 1 -type d ! -name "_templates" ! -name "_disabled*" -printf "%f\n" | jq -R -s -c 'split("\n")[:-1]')
          echo "${WORKER_NAMES}" | jq .
          echo "WORKER_MATRIX=${WORKER_NAMES}" >> "${GITHUB_OUTPUT}"

    outputs:
      worker_matrix: ${{ steps.generate_matrix.outputs.WORKER_MATRIX }}

  ##################################################
  # Wait for Workers to be deployed.
  ##################################################

  check:
    name: Thumbs Up/Down ${{ matrix.worker }}

    runs-on: ${{ matrix.os }}

    needs:
      - matrix

    timeout-minutes: 30
    continue-on-error: false

    strategy:
      fail-fast: true
      matrix:
        worker: ${{ fromJson(needs.matrix.outputs.worker_matrix) }}
        os:
          - ubuntu-latest

    steps:
      - id: wait_for_workers
        name: Wait for Workers
        uses: fountainhead/action-wait-for-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          checkName: Deploy Worker ${{ matrix.worker }}
          timeoutSeconds: 900

      - id: pr_comment_thumbs_up
        name: PR Comment (Thumbs Up)
        if: ${{ steps.wait_for_workers.outputs.conclusion == 'success' }}
        uses: exercism/pr-commenter-action@v1.5.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/pr-comments/thumbs_up.yaml
          template-variables: |
            {
              "id": "${{ github.sha }}-thumbs",
              "onCreate": "create",
              "onUpdate": "recreate"
            }

      - id: pr_comment_thumbs_down
        name: PR Comment (Thumbs Down)
        if: ${{ steps.wait_for_workers.outputs.conclusion != 'success' }}
        uses: exercism/pr-commenter-action@v1.5.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/pr-comments/thumbs_down.yaml
          template-variables: |
            {
              "id": "${{ github.sha }}-thumbs",
              "onCreate": "create",
              "onUpdate": "recreate"
            }
